
* solarpaq.com website

** About license
*** En español
Es un *SPA* hecho con ~elm-pages~ es público el repositorio, por si sirve les comparto la forma en que implanté y personalicé elm-pages.
Pero por [[https://www.notion.so/Tailwind-UI-License-644418bb34ad4fa29aac9b82e956a867][licencia]], estoy usando https://tailwindui.com/components y no permite copiar el diseño visula de la aplicación.

*** En Inglés
This is an *SPA* made with [[https://github.com/dillonkearns/elm-pages/][elm-pages]] with [[https://elm-lang.org/][elm programming language]]. Shared as a public repository if you what to check out how I used elm-pages for my needs. But regarding the visual layout of the web pages, it is done with https://tailwindui.com/components and it's  [[https://www.notion.so/Tailwind-UI-License-644418bb34ad4fa29aac9b82e956a867][licence]] doesn't allow to be copied as a template for other to use in their site.

** Notas particulares de la instalación del framework: elm-pages
*** Para la inInstalación base
Para incorporar las últimas mejoras entre releases, en package.json se hace referencia al subdirectorio  ~../elm-pages~, que es clonado de tal cual excepto una modificación:

Y en en  ~elm.json~ agregué referencia a ~elm-pages/src~ así:

#+begin_src json
"source-directories": [
        "src",
        "gen",
        "../elm-pages/src"
    ],
#+end_src

Adicionalmente instalé manualmente las dependencias que pide elm-pages.

En package.json también

#+begin_src json
  "devDependencies": {
    "elm-tooling": "^0.6.3",
    "elm-oembed": "0.0.6",
    "elm-pages": "file:../elm-pages"
}
#+end_src

**** Corrigiendo errorores
Al ejecutar ~$npx elm-pages-beta~:
Hay que instalar global "elm-optimize-level2"

**** Actualizaciones en lo futuro
Podemos actualizar el directorio clonado ~elm-pages~ para incorporar los cambios en este framework.
Independientemente podemos actualizar los archivos npm y los archivos de elm.

